name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: cooltrip
          POSTGRES_USER: symfony
          POSTGRES_PASSWORD: symfony
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Install PDO PostgreSQL driver
        run: |
          sudo apt-get update && sudo apt-get install -y libpq-dev
          sudo docker-php-ext-install pdo_pgsql

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libpq-dev && docker-php-ext-install pdo_pgsql
          composer install --prefer-dist --no-progress --no-suggest

      - name: Wait for DB to be ready
        run: |
          echo "Waiting for db to be ready..."
          sleep 10

      - name: Prepare database
        run: |
          export DATABASE_URL="postgresql://symfony:symfony@localhost:5432/cooltrip?serverVersion=15&charset=utf8"
          php bin/console doctrine:database:create --if-not-exists --env=test
          php bin/console doctrine:migrations:migrate --no-interaction --env=test

      - name: Check migrations status
        run: |
          export DATABASE_URL="postgresql://symfony:symfony@localhost:5432/cooltrip?serverVersion=15&charset=utf8"
          php bin/console doctrine:migrations:status --env=test

      - name: Apply migrations if available
        run: |
          export DATABASE_URL="postgresql://symfony:symfony@localhost:5432/cooltrip?serverVersion=15&charset=utf8"
          php bin/console doctrine:migrations:migrate --no-interaction --env=test || true

      - name: Run tests
        run: ./vendor/bin/simple-phpunit